#!/bin/sh -eu
# Ma_Sys.ma Shutdown script 3.0.1, Copyright (c) 2012, 2017, 2020 Ma_Sys.ma.
# For further info send an e-mail to Ma_Sys.ma@web.de.
#
# Maintenace:
# Keep these lines in your /etc/sudoers file:
#
#   Cmnd_Alias      SHUTDOWN = /usr/bin/mahalt
#   linux-fan       ALL=NOPASSWD: SHUTDOW
#
# You might need to replace "linux-fan" by your username.
# When using groups add a "%" before the group, e.g.: "%mahalters"

submsg() { printf '\033[1;36m-- %s :: %s --\033[0m\n' "$*" \
					"$(date "+%d.%m.%Y %H:%M:%S")"; }

if ! [ "$#" = 0 ] && { [ "$1" = "--help" ] || [ "$1" = "-h" ]; }; then
	head -n 4 "$0" | tail -n 3 | cut -c 3-
	cat <<EOF
USAGE $0 [-r|-f]

-r  Reboot instead of shutdown
-f  Fast -- skip execution of hooks from /usr/lib/mahalt.d
EOF
	exit 0
fi

if [ "$(id -u)" = 0 ]; then
	echo "mahalt$$: Got root permissions."

	if [ "$1" = "-f" ]; then
		echo "mahalt$$: Hooks skipped."
		shift
	else
		echo "mahalt$$: Invoking hooks..." | tee /var/log/mahalt
		for i in /usr/lib/mahalt.d/*; do
			[ -x "$i" ] || continue
			submsg "Run hook $(basename "$i")" | \
							tee -a /var/log/mahalt
			"$i" --by-mahalt 2>&1 | tee -a /var/log/mahalt
		done
		echo "mahalt$$: Hook execution complete." | \
							tee -a /var/log/mahalt
	fi

	echo "mahalt$$: Terminating Java applications..."
	killall -s TERM java || \
			echo "mahalt$$: No Java applications were running."

	echo "mahalt$$: syncing..."
	sync

	if [ "$1" = "-r" ]; then
		exec /sbin/reboot
	fi

	exec /sbin/halt -p
else
	echo "mahalt$$: Restarting with root permissions..."
	# Try sudo and use su on fail
	rv=0
	sudo "$0" "$@" || rv=$?
	if ! [ "$rv" = 0 ] && ! [ "$rv" = 64 ]; then
		exec su -c "$0 $*"
	fi
	exit "$rv"
fi
